### Numpy Practice

### Numpy Basics 

### Arrays

In [2]:
import numpy as np

In [9]:
print(np.__version__)

1.18.1


In [12]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sudhakar/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Sudhakar/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sudhakar/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mk

In [15]:
#info give the information of method wit sample
np.info(np.all)

 all(*args, **kwargs)

Test whether all array elements along a given axis evaluate to True.

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
axis : None or int or tuple of ints, optional
    Axis or axes along which a logical AND reduction is performed.
    The default (``axis=None``) is to perform a logical AND over all
    the dimensions of the input array. `axis` may be negative, in
    which case it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a reduction is performed on multiple
    axes, instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternate output array in which to place the result.
    It must have the same shape as the expected output and its
    type is preserved (e.g., if ``dtype(out)`` is float, the result
    will consist of 0.0's and 1.0's). See `ufuncs-output-type` for more
    details.

keepdims : bool, optional
    If this is set

In [24]:
#Find if none of the elements in an array is zero. All method returns True if there is no zero else False
nonzero_arr = np.array([1,2,3])
print("No zero in array: ",np.all(nonzero_arr))
nonzero_arr = np.array([1,2,3,0])
print("No zero in array: ",np.all(nonzero_arr))

No zero in array:  True
No zero in array:  False


In [25]:
#Find if none of the elements in an array is nonzero. Any method returns True if there are no non-zero else False
zero_array = np.array([1,0,0,0])
print("non-zero in array :",np.any(zero_array))
zero_array = np.array([0,0,0,0])
print("non-zero in array:",np.any(zero_array))

non-zero in array : True
non-zero in array: False


In [26]:
arr = np.array([1,2,4])
print(arr)

[1 2 4]


In [29]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


In [31]:
#Create a 3*3 array using list_1 = [1,2,3] list_2 = [4,5,6] list_3 = [7,8,9]
list_1=[1,2,3]
list_2=[3,4,5]
list_3=[7,8,9]
list_arr = np.array([list_1,list_2,list_3])
print(list_arr)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [37]:
#product of 2 mist using lambda 
list_1 = [1,2,3,4]
list_2 = [5,6,7,8]

product_list = list(map(lambda x,y : x*y, list_1,list_2))
print(product_list)

#Same can be done using numpy 
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

pro_numpy_array = arr_1*arr_2
print(pro_numpy_array)


[5, 12, 21, 32]
[ 5 12 21 32]


In [48]:
#Perform an element-wise multiplication using list_1 = [2,3,4,5] list_2 = [7,8,9,6] and obtain the output as a list. 
#Hint: Convert the list to an array and after multiplication convert it back to a list.

list_1 = [2,3,4,5]
list_2 = [7,8,9,6]

arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

pro_array = arr_1*arr_2
print(list(pro_array))

add_array = arr_1+arr_2
print(add_array)

sub_array = arr_2-arr_1
print(sub_array)

div_array = arr_1/arr_2
print(div_array)

sqr_array = arr_2**2
print(sqr_array)

#Note : while binary operation both the array size should be equal

[14, 24, 36, 30]
[ 9 11 13 11]
[5 5 5 1]
[0.28571429 0.375      0.44444444 0.83333333]
[49 64 81 36]


### NumPy Arrays using predefined functions 

The following ways are commonly used:

<b>np.ones()</b>: Create an array of 1s

<b>np.zeros()</b>: Create an array of 0s

<b>np.random.random()</b>: Create an array of random numbers between 0 and 1

<b>np.arange()</b>: Create an array with increments of a fixed step size

<b>np.linspace()</b>: Create an array of fixed length

In [70]:
#3 rows 2 cols (3x2 matrix)
#Default generates was float/decimal 1's to make it spect to int we should specify it as dtype in syntax 
np.ones((3,2), dtype = np.int)


array([[1, 1],
       [1, 1],
       [1, 1]])

In [71]:
#Default generates was float/decimal 0's to make it spect to int we should specify it as dtype in syntax 
np.zeros([2,5], dtype = int)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [74]:
np.random.random([3,4])

array([[0.33144249, 0.96362018, 0.9304364 , 0.73833508],
       [0.49332924, 0.73724712, 0.59431884, 0.98320091],
       [0.23345755, 0.24880034, 0.54313521, 0.29372687]])

In [78]:
#generates numbers starting from 10 to 100 with interval of 5 
numbers = np.arange(10, 100, 5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [85]:
#creates an array 
np.linspace((10,100,10))


TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

Apart from the functions mentioned in the video, there are a few more useful functions for creating arrays, such as: 

<b>np.full()</b>: Create a constant array of any number ‘n’

<b>np.tile()</b>: Create a new array — by repeating an existing array — for a particular number of times

<b>np.eye()</b>: Create an identity matrix of any dimension

<b>np.random.randint()</b>: Create a random array of integers within a particular range

In [88]:

int_x = 5
rows_m = 3
cols_n = 4

np.full((rows_m,cols_n),int_x)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [89]:
np.tile(int_x,(rows_m,cols_n))

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [90]:
#Create an array of first 10 multiples of 5 using the 'arange' function.
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [105]:
#Given an even integer ‘n’, create an ‘n*n’ checkerboard matrix with the values 0 and 1, using the tile function.
arr = np.array([[0,1],[1,0]])
n = 5
np.tile(arr,(n//2,n//2))


(2, 2)

### Structure and Content of Arrays
It is helpful to inspect the structure of NumPy arrays, especially while working with large arrays. Some attributes of 

NumPy arrays are:

<b>shape</b>: Shape of array (n x m)

<b>dtype</b>: data type (int, float etc.)

<b>ndim</b>: Number of dimensions (or axes)

<b>itemsize</b>: Memory used by each array element in bytes

In [104]:
np.shape

<function numpy.shape(a)>

In [114]:
rand_array = np.random.random([1000,300])
print(rand_array[1])

[0.96770297 0.25937925 0.8310909  0.04983466 0.03810899 0.06848779
 0.55213602 0.46875592 0.95029683 0.38754819 0.48333623 0.09841486
 0.65992024 0.33276816 0.24316488 0.46455224 0.98860465 0.53015661
 0.86113555 0.38547692 0.96582436 0.81274246 0.60139005 0.67915756
 0.73150237 0.29228247 0.84295568 0.56008202 0.00419409 0.08078103
 0.85693261 0.09470668 0.25330274 0.85629814 0.8499982  0.25404984
 0.99393892 0.58124631 0.1764314  0.09094848 0.9137605  0.96955142
 0.73991509 0.12975993 0.46194577 0.42113696 0.26924458 0.24470065
 0.62993128 0.10190214 0.96617672 0.59006935 0.92524533 0.86162588
 0.85947724 0.5373102  0.43994585 0.58954266 0.659758   0.29550629
 0.92763562 0.87087146 0.38380607 0.37192802 0.34591648 0.97825693
 0.73103861 0.76882833 0.92728076 0.73243933 0.30957521 0.96676483
 0.24215321 0.94786489 0.70798634 0.36948216 0.71416321 0.00251104
 0.50558312 0.57150785 0.45281286 0.8852426  0.17288996 0.51581665
 0.1484497  0.87997837 0.26480311 0.58107254 0.24677535 0.5900

In [110]:
rand_array.shape

(1000, 300)

In [115]:
rand_array.ndim

2

In [116]:
rand_array.dtype

dtype('float64')

In [117]:
rand_array.itemsize

8

In [119]:
#3d Array 
array_3d = np.arange(24).reshape(2,3,4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [120]:
#Create an array using list list_1 = [10,11,12,13] and list_2 = [15,12,13,14] and print the shape and dimension of the array created.

### Subset, Slice, Index and Iterate through Arrays
Let's now look at how to access the elements of an array. For one-dimensional arrays, indexing, slicing etc. is similar to python lists - indexing starts at 0.

In [131]:
array_1 = np.arange(1,10)
print(array_1)

[1 2 3 4 5 6 7 8 9]


In [132]:
array_1[2]

3

In [133]:
array_1[1:5]

array([2, 3, 4, 5])

In [134]:
array_1[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [135]:
array_1[:3]

array([1, 2, 3])

In [138]:
array_1[1::2]

array([2, 4, 6, 8])

### Multidimensional Arrays
Multidimensional arrays are indexed using as many indices as the number of dimensions or axes. For instance, to index a 2-D array, you need two indices - array[x, y].

In [153]:
array_2d = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]


In [148]:
array_2d[2,:]

array([2, 4, 6, 8])

In [149]:
array_2d[:,3]

array([4, 8, 8])

In [158]:
array_2d[2:,2:]

array([[6, 8]])

array([1, 2, 3, 4])

In [187]:
#Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, 
#last row of the input array respectively.

#first column
print(array_2d[:,0])

#first row
print(array_2d[0,])

#last column
print(array_2d[:,3])

#last row
print(array_2d[2,])

[1 5 2]
[1 2 3 4]
[4 8 8]
[2 4 6 8]


### Operations on NumPy Arrays

The learning objectives of this section are:

Manipulate arrays

Reshape arrays

Stack arrays

Perform operations on arrays

Perform basic mathematical operations

Apply built-in functions

Apply your own functions

Apply basic linear algebra operations

### Manipulating Arrays

Let's look at some ways to manipulate arrays, i.e. changing the shape, combining and splitting arrays, etc.   

#### Reshaping Arrays

Reshaping is done using the ```reshape()``` function.


In [192]:
arr = np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [195]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 4 into shape (2,6)